### ISSUE TITLE
issues with chef omnibus install

### ISSUE THREAD

**Issue by bixu** [test-kitchen/kitchen-joyent#2]
getting errors like this:

```
>>>>>> Converge failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (3) for command: [sh -c '
        # Check whether a command exists - returns 0 if it does, 1 if it does not
        exists() {
if command -v $1 >/dev/null 2>&1
then
  return 0
else
  return 1
fi
        }

        # do_wget URL FILENAME
        do_wget() {
echo "trying wget..."
wget -O "$2" "$1" 2>/tmp/stderr
# check for bad return status
test $? -ne 0 && return 1
# check for 404 or empty file
grep "ERROR 404" /tmp/stderr 2>&1 >/dev/null
if test $? -eq 0 || test ! -s "$2"; then
  return 1
fi
return 0
        }

        # do_curl URL FILENAME
        do_curl() {
echo "trying curl..."
curl -L "$1" > "$2"
# check for bad return status
[ $? -ne 0 ] && return 1
# check for bad output or empty file
grep "The specified key does not exist." "$2" 2>&1 >/dev/null
if test $? -eq 0 || test ! -s "$2"; then
  return 1
fi
return 0
        }

        # do_fetch URL FILENAME
        do_fetch() {
echo "trying fetch..."
fetch -o "$2" "$1" 2>/tmp/stderr
# check for bad return status
test $? -ne 0 && return 1
return 0
        }

        # do_perl URL FILENAME
        do_perl() {
echo "trying perl..."
perl -e "use LWP::Simple; getprint($ARGV[0]);" "$1" > "$2"
# check for bad return status
test $? -ne 0 && return 1
# check for bad output or empty file
# grep "The specified key does not exist." "$2" 2>&1 >/dev/null
# if test $? -eq 0 || test ! -s "$2"; then
#   unable_to_retrieve_package
# fi
return 0
        }

        # do_python URL FILENAME
        do_python() {
echo "trying python..."
python -c "import sys,urllib2 ; sys.stdout.write(urllib2.urlopen(sys.argv[1]).read())" "$1" > "$2"
# check for bad return status
test $? -ne 0 && return 1
# check for bad output or empty file
#grep "The specified key does not exist." "$2" 2>&1 >/dev/null
#if test $? -eq 0 || test ! -s "$2"; then
#  unable_to_retrieve_package
#fi
return 0
        }

        # do_download URL FILENAME
        do_download() {
PATH=/opt/local/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
export PATH

echo "downloading $1"
echo "  to file $2"

# we try all of these until we get success.
# perl, in particular may be present but LWP::Simple may not be installed

if exists wget; then
  do_wget $1 $2 && return 0
fi

if exists curl; then
  do_curl $1 $2 && return 0
fi

if exists fetch; then
  do_fetch $1 $2 && return 0
fi

if exists perl; then
  do_perl $1 $2 && return 0
fi

if exists python; then
  do_python $1 $2 && return 0
fi

echo ">>>>>> wget, curl, fetch, perl or python not found on this instance."
return 16
        }


should_update_chef() {
  case "11.16.4" in
    true|`chef-solo -v | cut -d " " -f 2`) return 1 ;;
    latest|*) return 0 ;;
  esac
}

if [ ! -d "/opt/chef" ] || should_update_chef ; then
  echo "-----> Installing Chef Omnibus (11.16.4)"
  do_download https://www.getchef.com/chef/install.sh /tmp/install.sh
  sudo -E sh /tmp/install.sh -v 11.16.4
fi'
]
>>>>>> ----------------------
```

my .kitchen.yml looks like this:

```
cat .kitchen.yml
---
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_plugin: joyent
    driver_config:
      joyent_username: <%= ENV['MANTA_USER'] %>
      joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
      joyent_keyname: <%= ENV['MANTA_KEY_ID'] %>
      joyent_url: <%= ENV['JOYENT_API_URL'] %>
      require_chef_omnibus: "11.16.4"
    provisioner:
      name: chef_zero
      sudo: true

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
```

**Comment by sax** [comment]
I think you need to include a link to the chef_omnibus_url:

https://github.com/wanelo-chef/circonus-checks/blob/master/.kitchen.yml#L17

On Fri, Jan 16, 2015 at 8:46 AM, Blake Irvin <notifications@github.com>
wrote:

> getting errors like this (looks like i'm still getting the normal omnibus
> bootstrap, which i should not be):
>
> kitchen test
> -----> Starting Kitchen (v1.2.1)
> -----> Cleaning up any prior instances of <default-smartos-base64-1430>
> -----> Destroying <default-smartos-base64-1430>...
>        Finished destroying <default-smartos-base64-1430> (0m0.00s).
> -----> Testing <default-smartos-base64-1430>
> -----> Creating <default-smartos-base64-1430>...
>        Joyent <84b2f5f7-9825-e4d2-e2ef-ecf99eb1a7ab> created.
> .............       (server ready)
>        (ssh ready)
>
>        Finished creating <default-smartos-base64-1430> (0m52.30s).
> -----> Converging <default-smartos-base64-1430>...
>        Preparing files for transfer
>        Preparing current project directory as a cookbook
>        Removing non-cookbook files before transfer
> -----> Installing Chef Omnibus (true)
>        downloading https://www.getchef.com/chef/install.sh
>          to file /tmp/install.sh
>        trying wget...
>        /tmp/install.sh: line 87: syntax error at line 172: ` ' unexpected
> >>>>>> Converge failed on instance <default-ubuntu-1204>.
> >>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
> >>>>>> ------Exception-------
> >>>>>> Class: Kitchen::ActionFailed
> >>>>>> Message: SSH exited (3) for command: [sh -c '
>         # Check whether a command exists - returns 0 if it does, 1 if it does not
>         exists() {
> if command -v $1 >/dev/null 2>&1
> then
>   return 0
> else
>   return 1
> fi
>         }
>
>         # do_wget URL FILENAME
>         do_wget() {
> echo "trying wget..."
> wget -O "$2" "$1" 2>/tmp/stderr
> # check for bad return status
> test $? -ne 0 && return 1
> # check for 404 or empty file
> grep "ERROR 404" /tmp/stderr 2>&1 >/dev/null
> if test $? -eq 0 || test ! -s "$2"; then
>   return 1
> fi
> return 0
>         }
>
>         # do_curl URL FILENAME
>         do_curl() {
> echo "trying curl..."
> curl -L "$1" > "$2"
> # check for bad return status
> [ $? -ne 0 ] && return 1
> # check for bad output or empty file
> grep "The specified key does not exist." "$2" 2>&1 >/dev/null
> if test $? -eq 0 || test ! -s "$2"; then
>   return 1
> fi
> return 0
>         }
>
>         # do_fetch URL FILENAME
>         do_fetch() {
> echo "trying fetch..."
> fetch -o "$2" "$1" 2>/tmp/stderr
> # check for bad return status
> test $? -ne 0 && return 1
> return 0
>         }
>
>         # do_perl URL FILENAME
>         do_perl() {
> echo "trying perl..."
> perl -e "use LWP::Simple; getprint($ARGV[0]);" "$1" > "$2"
> # check for bad return status
> test $? -ne 0 && return 1
> # check for bad output or empty file
> # grep "The specified key does not exist." "$2" 2>&1 >/dev/null
> # if test $? -eq 0 || test ! -s "$2"; then
> #   unable_to_retrieve_package
> # fi
> return 0
>         }
>
>         # do_python URL FILENAME
>         do_python() {
> echo "trying python..."
> python -c "import sys,urllib2 ; sys.stdout.write(urllib2.urlopen(sys.argv[1]).read())" "$1" > "$2"
> # check for bad return status
> test $? -ne 0 && return 1
> # check for bad output or empty file
> #grep "The specified key does not exist." "$2" 2>&1 >/dev/null
> #if test $? -eq 0 || test ! -s "$2"; then
> #  unable_to_retrieve_package
> #fi
> return 0
>         }
>
>         # do_download URL FILENAME
>         do_download() {
> PATH=/opt/local/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
> export PATH
>
> echo "downloading $1"
> echo "  to file $2"
>
> # we try all of these until we get success.
> # perl, in particular may be present but LWP::Simple may not be installed
>
> if exists wget; then
>   do_wget $1 $2 && return 0
> fi
>
> if exists curl; then
>   do_curl $1 $2 && return 0
> fi
>
> if exists fetch; then
>   do_fetch $1 $2 && return 0
> fi
>
> if exists perl; then
>   do_perl $1 $2 && return 0
> fi
>
> if exists python; then
>   do_python $1 $2 && return 0
> fi
>
> echo ">>>>>> wget, curl, fetch, perl or python not found on this instance."
> return 16
>         }
>
>
> should_update_chef() {
>   case "11.16.4" in
>     true|`chef-solo -v | cut -d " " -f 2`) return 1 ;;
>     latest|*) return 0 ;;
>   esac
> }
>
> if [ ! -d "/opt/chef" ] || should_update_chef ; then
>   echo "-----> Installing Chef Omnibus (11.16.4)"
>   do_download https://www.getchef.com/chef/install.sh /tmp/install.sh
>   sudo -E sh /tmp/install.sh -v 11.16.4
> fi'
> ]
> >>>>>> ----------------------
>
> my .kitchen.yml looks like this:
>
> cat .kitchen.yml
> ---
> provisioner:
>   name: chef_solo
>
> platforms:
>   - name: ubuntu-12.04
>     driver_plugin: joyent
>     driver_config:
>       joyent_username: <%= ENV['MANTA_USER'] %>
>       joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
>       joyent_keyname: <%= ENV['MANTA_KEY_ID'] %>
>       joyent_url: <%= ENV['JOYENT_API_URL'] %>
>       require_chef_omnibus: "11.16.4"
>     provisioner:
>       name: chef_zero
>       sudo: true
>
> suites:
>   - name: default
>     run_list:
>       - recipe[git::default]
>     attributes:
>
> cc/ @sax <https://github.com/sax> @someara <https://github.com/someara>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/test-kitchen/kitchen-joyent/issues/2>.
>



-- 
----
e s

**Comment by bixu** [comment]
But I am - pasted the wrong .kitchent.yml  - update coming...

**Comment by bixu** [comment]
so i really don't think the plugin is respecting that custom url for the chef 'omnibus' installer

**Comment by bixu** [comment]
it looks like the 'chef_omnibus_url:' attribute MUST be nested under 'provisioner:' or the plugin will not work...

**Comment by bixu** [comment]
this exact formatting of .kitchen.yml seems to work for a multi-platform setup:
```
---
driver_plugin: joyent
driver_config:
  joyent_username: <%= ENV['MANTA_USER'] %>
  joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
  joyent_keyname: <%= ENV['MANTA_KEY_ID'] %>
  joyent_url: <%= ENV['JOYENT_API_URL'] %>

platforms:
- name: smartos_base64_1430
  driver_config:
    joyent_image_id: 62f148f8-6e84-11e4-82c5-efca60348b9f
    joyent_flavor_id: g3-highcpu-1.75-smartos
  provisioner:
    name: chef_zero
    sudo: true
    require_chef_omnibus: true
    chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/latest.sh

- name: ubuntu_1204_20140519
  driver_config:
    joyent_image_id: 0fd57f23-bc80-4bde-8ab2-64acf8a14fe9
    joyent_flavor_id: g3-highcpu-1.75-kvm
    username: ubuntu
  provisioner:
    name: chef_zero
    sudo: true
    require_chef_omnibus: '11.16.4'

suites:
- name: default
  run_list: ["recipe[git]"]
```
